replicaCount: 3

image:
  repository: nginx
  tag: latest
  pullPolicy: Always

security:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000
  readOnlyRootFilesystem: true

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []

config:
  environment: production
  log_level: info 