apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: web-app-psp
  namespace: secure-app
spec:
  privileged: false
  # Empêche l'escalade de privilèges
  allowPrivilegeEscalation: false
  # Exige des conteneurs non-root
  runAsUser:
    rule: MustRunAsNonRoot
  # Exige des conteneurs en lecture seule
  readOnlyRootFilesystem: true
  # Restreint les capacités Linux
  allowedCapabilities: []
  # Exige des volumes en lecture seule
  volumes:
  - configMap
  - secret
  - emptyDir
  # Restreint les types de volumes autorisés
  hostNetwork: false
  hostIPC: false
  hostPID: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535
  fsGroup:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535 