apiVersion: v1
kind: Secret
metadata:
  name: web-app-secrets
  namespace: secure-app
type: Opaque
data:
  # Les valeurs sont encodées en base64
  api-key: YWJjMTIzCg==  # abc123 encodé en base64
  db-password: ZGV2c2Vjb3BzCg==  # devsecops encodé en base64 